### PR TITLE
Add support for S3 custom endpoint

### PR DESCRIPTION
**Pull request by francois-travais**
Add support for non-AWS hosted S3-like services such as Digital Ocean spaces for instance.

### CODE REVIEW

**Comment by dehy** [comment]
I did not review the code itself but I built this PR and tested locally. It works as expected! Thank you :)

**Comment by dehy** [comment]
I think it's a side effect not strictly related to this PR. It just reveals it. I can create a separate issue if necessary.

The alternate S3 provider I use does not support server-side encryption and although I did not set the parameter `structurizr.encryption` property, I got this error message when creating a review:

```
[http-nio-8080-exec-3] AmazonWebServicesS3ReviewDao - com.amazonaws.services.s3.model.AmazonS3Exception: Server-side encryption is not supported. (Service: Amazon S3; Status Code: 501; Error Code: NotImplemented; Request ID: tx85efe787a92a4d3c80ba4-00645400a7; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
com.structurizr.onpremises.component.review.ReviewComponentException: Could not create review
```

My properties file
```
structurizr.url=http://localhost:8080
structurizr.data=aws-s3
aws-s3.endpoint=s3.fr-par.scw.cloud
aws-s3.accessKeyId=<redacted>
aws-s3.secretAccessKey=<redacted>
aws-s3.region=fr-par
aws-s3.bucketName=dehy-test-structurizr
```

The file is uploaded to the S3 bucket but it fails just after and the review is not created.
I did not see any specific information in documentation (like "if storage is s3, encryption is activated")
I had not problem when creating a diagram workspace and importing JSON.

**Comment by simonbrowndotje** [comment]
Thanks ... I will merge the PR and fix the server-side encryption issue (IIRC, this can be set on the bucket if needed, when it's created).

**Comment by simonbrowndotje** [comment]
Thanks @francois-travais!

**Pull request merged**
